/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.risav.library_management_system.books;

//import java.lang.System.Logger;
import com.risav.library_management_system.admin.LoginPage;
import java.sql.*;
import javax.swing.*;
import java.util.logging.Logger;
import java.util.logging.Level;


/**
 *
 * @author MSi
 */
public class AddBooks extends javax.swing.JFrame {

    /**
     * Creates new form AddBooks
     */
    public AddBooks() {
        initComponents();
        setDefaultCloseOperation(AddBooks.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        booksQuantityLabel = new javax.swing.JLabel();
        booksNameLabel = new javax.swing.JLabel();
        booksAuhtorLabel = new javax.swing.JLabel();
        booksCategoryLabel = new javax.swing.JLabel();
        booksAuthorField = new javax.swing.JTextField();
        booksNameField = new javax.swing.JTextField();
        publishedYearField = new javax.swing.JTextField();
        booksCategoryField = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        availableCopiesField = new javax.swing.JTextField();
        booksQuantityLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        booksQuantityLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        booksQuantityLabel.setText("Published Year");

        booksNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        booksNameLabel.setText("Books Name :");

        booksAuhtorLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        booksAuhtorLabel.setText("Books Auhtor :");

        booksCategoryLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        booksCategoryLabel.setText("Books Category :");

        booksAuthorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksAuthorFieldActionPerformed(evt);
            }
        });

        booksNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksNameFieldActionPerformed(evt);
            }
        });

        publishedYearField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publishedYearFieldActionPerformed(evt);
            }
        });

        booksCategoryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksCategoryFieldActionPerformed(evt);
            }
        });

        SubmitButton.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        clearButton.setText("Clear ");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        backButton.setText("Close");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Books");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        availableCopiesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availableCopiesFieldActionPerformed(evt);
            }
        });

        booksQuantityLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        booksQuantityLabel1.setText("Books Copies :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(booksAuhtorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(booksNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(booksCategoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(booksQuantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(booksQuantityLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(booksCategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(publishedYearField, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(booksAuthorField, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(booksNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(availableCopiesField, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(booksNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(booksNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(booksAuhtorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(booksAuthorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(booksCategoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(booksCategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(publishedYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(booksQuantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(booksQuantityLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(availableCopiesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void booksAuthorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksAuthorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_booksAuthorFieldActionPerformed

    private void booksNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_booksNameFieldActionPerformed

    private void publishedYearFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publishedYearFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_publishedYearFieldActionPerformed

    private void booksCategoryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksCategoryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_booksCategoryFieldActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        booksNameField.setText(null);
        booksAuthorField.setText(null);
        booksCategoryField.setText(null);
        publishedYearField.setText(null);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:mysql://localhost:3306/lib_man_sys?useSSL=false";
        String mysql_username = "risav";
        String mysql_password = "1234";
        String query = "INSERT INTO books VALUES(?,?,?,?)";
        String title = booksNameField.getText();
        String author = booksAuthorField.getText();
        String genre = booksCategoryField.getText();
        int published_year= Integer.parseInt(publishedYearField.getText());
        int available_copies = Integer.parseInt(availableCopiesField.getText());
        String checkQuery = "UPDATE books set available_copies= available_copies+" + available_copies + "WHERE title='" + title + "' and genre='" + genre + "' and author='" + author + "';";
        try {
            Connection conn = DriverManager.getConnection(url, mysql_username, mysql_password);
            Statement chckstm = conn.createStatement();
            int rows = chckstm.executeUpdate(checkQuery);
            
            if(rows>0) {
                JOptionPane.showMessageDialog(this, "Books available_copies updated.");
            } else {
                PreparedStatement stm= conn.prepareCall(query);
                stm.setString(1, title);
                stm.setString(2, author);
                stm.setString(3, genre);
                stm.setInt(4, available_copies);
                stm.execute();
                JOptionPane.showMessageDialog(this, "Books Details added Successfully.");
            }

            booksNameField.setText(null);
            booksAuthorField.setText(null);
            booksCategoryField.setText(null);
            publishedYearField.setText(null);

//        } catch (SQLException ex) {
        } catch (Exception ex) { //remove this exception and uncomment uppper catch statement

            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Exceptoin"+ ex);
        }

    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void availableCopiesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availableCopiesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availableCopiesFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SubmitButton;
    private javax.swing.JTextField availableCopiesField;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel booksAuhtorLabel;
    private javax.swing.JTextField booksAuthorField;
    private javax.swing.JTextField booksCategoryField;
    private javax.swing.JLabel booksCategoryLabel;
    private javax.swing.JTextField booksNameField;
    private javax.swing.JLabel booksNameLabel;
    private javax.swing.JLabel booksQuantityLabel;
    private javax.swing.JLabel booksQuantityLabel1;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField publishedYearField;
    // End of variables declaration//GEN-END:variables
}
